// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fanfnir_back.Models;

#nullable disable

namespace fanfnir_back.Migrations
{
    [DbContext(typeof(FafnirContext))]
    [Migration("20260830130154_AddCofrinhoYieldFields")]
    partial class AddCofrinhoYieldFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fanfnir_back.Models.AportesMetas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAporte")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("FkIdCarteira")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdMeta")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id")
                        .HasName("AportesMetas_pkey");

                    b.HasIndex("FkIdCarteira");

                    b.HasIndex(new[] { "FkIdMeta", "DataAporte" }, "IX_AportesMetas_Meta_DataAporte")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "FkIdUsuario", "FkIdCarteira" }, "IX_AportesMetas_Usuario_Carteira");

                    b.ToTable("AportesMetas", t =>
                        {
                            t.HasComment("Histórico de aportes realizados para metas financeiras.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.Assinaturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("DiaCobranca")
                        .HasColumnType("smallint");

                    b.Property<int>("FkIdCarteira")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id")
                        .HasName("Assinaturas_pkey");

                    b.HasIndex("FkIdCarteira");

                    b.HasIndex("FkIdCategoria");

                    b.HasIndex(new[] { "FkIdUsuario", "Ativa", "DiaCobranca" }, "IX_Assinaturas_Usuario_Ativa_DiaCobranca");

                    b.HasIndex(new[] { "FkIdUsuario", "FkIdCarteira" }, "IX_Assinaturas_Usuario_Carteira");

                    b.ToTable("Assinaturas", t =>
                        {
                            t.HasComment("Cobranças recorrentes do usuário, úteis para previsão financeira.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FkIdConexao")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("InstituicaoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstituicaoNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProvedorContaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SaldoAtual")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("SaldoDisponivel")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UltimaSincronizacao")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("ContasBancarias_pkey");

                    b.HasIndex(new[] { "FkIdConexao" }, "IX_ContasBancarias_FkIdConexao");

                    b.HasIndex(new[] { "FkIdUsuario" }, "IX_ContasBancarias_FkIdUsuario");

                    b.HasIndex(new[] { "Provedor", "ProvedorContaId" }, "UX_ContasBancarias_Provedor_ContaId")
                        .IsUnique();

                    b.ToTable("ContasBancarias", (string)null);
                });

            modelBuilder.Entity("fanfnir_back.Models.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EstabelecimentoNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("FkIdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdContaBancaria")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProvedorTransacaoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id")
                        .HasName("TransacoesBancarias_pkey");

                    b.HasIndex(new[] { "FkIdCategoria" }, "IX_TransacoesBancarias_FkIdCategoria");

                    b.HasIndex(new[] { "FkIdContaBancaria" }, "IX_TransacoesBancarias_FkIdContaBancaria");

                    b.HasIndex(new[] { "FkIdUsuario" }, "IX_TransacoesBancarias_FkIdUsuario");

                    b.HasIndex(new[] { "Provedor", "ProvedorTransacaoId", "FkIdContaBancaria" }, "UX_TransacoesBancarias_Provedor_Transacao_Conta")
                        .IsUnique();

                    b.ToTable("TransacoesBancarias", (string)null);
                });

            modelBuilder.Entity("fanfnir_back.Models.Carteiras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Rende")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SaldoInicial")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValueSql("0.00");

                    b.Property<decimal?>("TaxaRendimento")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoRendimento")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoProcessamentoRendimento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("Carteiras_pkey");

                    b.HasIndex(new[] { "FkIdUsuario", "Ativo" }, "IX_Carteiras_Usuario_Ativo");

                    b.ToTable("Carteiras", t =>
                        {
                            t.HasComment("Carteiras, contas ou meios onde o saldo do usuário é controlado.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.Categorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("FkIdUsuario")
                        .HasColumnType("integer")
                        .HasComment("Nulo indica categoria padrão/global do sistema.");

                    b.Property<string>("Icone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("Categorias_pkey");

                    b.HasIndex(new[] { "FkIdUsuario", "Ativo" }, "IX_Categorias_Usuario_Ativo");

                    b.ToTable("Categorias", t =>
                        {
                            t.HasComment("Categorias globais e personalizadas para classificação de receitas e despesas.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.Metas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoReferencia")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Concluida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<short?>("MesReferencia")
                        .HasColumnType("smallint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoMeta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ValorAlvo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("ValorAtual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValueSql("0.00");

                    b.HasKey("Id")
                        .HasName("Metas_pkey");

                    b.HasIndex(new[] { "FkIdUsuario", "Ativa", "Concluida" }, "IX_Metas_Usuario_Ativa_Concluida");

                    b.HasIndex(new[] { "FkIdUsuario", "AnoReferencia", "MesReferencia" }, "IX_Metas_Usuario_Mes_Ano");

                    b.ToTable("Metas", t =>
                        {
                            t.HasComment("Objetivos financeiros do usuário, com acompanhamento de progresso.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.OpenFinanceConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("InstituicaoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstituicaoNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProvedorItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("OpenFinanceConexoes_pkey");

                    b.HasIndex(new[] { "FkIdUsuario" }, "IX_OpenFinanceConexoes_FkIdUsuario");

                    b.HasIndex(new[] { "ProvedorItemId" }, "IX_OpenFinanceConexoes_ProvedorItemId")
                        .IsUnique();

                    b.ToTable("OpenFinanceConexoes", (string)null);
                });

            modelBuilder.Entity("fanfnir_back.Models.OrcamentosMensais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FkIdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<short>("MesReferencia")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ValorLimite")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id")
                        .HasName("OrcamentosMensais_pkey");

                    b.HasIndex("FkIdCategoria");

                    b.HasIndex(new[] { "FkIdUsuario", "AnoReferencia", "MesReferencia" }, "IX_OrcamentosMensais_Usuario_Mes_Ano");

                    b.HasIndex(new[] { "FkIdUsuario", "FkIdCategoria", "AnoReferencia", "MesReferencia" }, "UX_OrcamentosMensais_Usuario_Categoria_Mes_Ano")
                        .IsUnique();

                    b.ToTable("OrcamentosMensais", t =>
                        {
                            t.HasComment("Limites mensais por categoria para controle de orçamento.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.Transacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FkIdCarteira")
                        .HasColumnType("integer");

                    b.Property<int?>("FkIdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<short>("MesReferencia")
                        .HasColumnType("smallint");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id")
                        .HasName("Transacoes_pkey");

                    b.HasIndex("FkIdCarteira");

                    b.HasIndex("FkIdCategoria");

                    b.HasIndex(new[] { "Tipo", "AnoReferencia", "MesReferencia" }, "IX_Transacoes_Tipo_Mes_Ano");

                    b.HasIndex(new[] { "FkIdUsuario", "FkIdCarteira", "AnoReferencia", "MesReferencia" }, "IX_Transacoes_Usuario_Carteira_Mes_Ano");

                    b.HasIndex(new[] { "FkIdUsuario", "FkIdCategoria", "AnoReferencia", "MesReferencia" }, "IX_Transacoes_Usuario_Categoria_Mes_Ano");

                    b.HasIndex(new[] { "FkIdUsuario", "DataTransacao" }, "IX_Transacoes_Usuario_DataTransacao")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "FkIdUsuario", "AnoReferencia", "MesReferencia" }, "IX_Transacoes_Usuario_Mes_Ano");

                    b.ToTable("Transacoes", t =>
                        {
                            t.HasComment("Lançamentos financeiros utilizados em extrato, dashboard e relatórios mensais.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Hash da senha gerado pela aplicação; nunca persistir senha em texto puro.");

                    b.HasKey("Id")
                        .HasName("Usuarios_pkey");

                    b.ToTable("Usuarios", t =>
                        {
                            t.HasComment("Usuários proprietários dos dados financeiros.");
                        });
                });

            modelBuilder.Entity("fanfnir_back.Models.AportesMetas", b =>
                {
                    b.HasOne("fanfnir_back.Models.Carteiras", "FkIdCarteiraNavigation")
                        .WithMany("AportesMetas")
                        .HasForeignKey("FkIdCarteira")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("fanfnir_back.Models.Metas", "FkIdMetaNavigation")
                        .WithMany("AportesMetas")
                        .HasForeignKey("FkIdMeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("AportesMetas")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdCarteiraNavigation");

                    b.Navigation("FkIdMetaNavigation");

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.Assinaturas", b =>
                {
                    b.HasOne("fanfnir_back.Models.Carteiras", "FkIdCarteiraNavigation")
                        .WithMany("Assinaturas")
                        .HasForeignKey("FkIdCarteira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Categorias", "FkIdCategoriaNavigation")
                        .WithMany("Assinaturas")
                        .HasForeignKey("FkIdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("Assinaturas")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdCarteiraNavigation");

                    b.Navigation("FkIdCategoriaNavigation");

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.BankAccount", b =>
                {
                    b.HasOne("fanfnir_back.Models.OpenFinanceConnection", "FkIdConexaoNavigation")
                        .WithMany("BankAccounts")
                        .HasForeignKey("FkIdConexao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdConexaoNavigation");

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.BankTransaction", b =>
                {
                    b.HasOne("fanfnir_back.Models.Categorias", "FkIdCategoriaNavigation")
                        .WithMany()
                        .HasForeignKey("FkIdCategoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("fanfnir_back.Models.BankAccount", "FkIdContaBancariaNavigation")
                        .WithMany("BankTransactions")
                        .HasForeignKey("FkIdContaBancaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdCategoriaNavigation");

                    b.Navigation("FkIdContaBancariaNavigation");

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.Carteiras", b =>
                {
                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("Carteiras")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.Categorias", b =>
                {
                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("Categorias")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.Metas", b =>
                {
                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("Metas")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.OpenFinanceConnection", b =>
                {
                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.OrcamentosMensais", b =>
                {
                    b.HasOne("fanfnir_back.Models.Categorias", "FkIdCategoriaNavigation")
                        .WithMany("OrcamentosMensais")
                        .HasForeignKey("FkIdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("OrcamentosMensais")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdCategoriaNavigation");

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.Transacoes", b =>
                {
                    b.HasOne("fanfnir_back.Models.Carteiras", "FkIdCarteiraNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("FkIdCarteira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fanfnir_back.Models.Categorias", "FkIdCategoriaNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("FkIdCategoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("fanfnir_back.Models.Usuarios", "FkIdUsuarioNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkIdCarteiraNavigation");

                    b.Navigation("FkIdCategoriaNavigation");

                    b.Navigation("FkIdUsuarioNavigation");
                });

            modelBuilder.Entity("fanfnir_back.Models.BankAccount", b =>
                {
                    b.Navigation("BankTransactions");
                });

            modelBuilder.Entity("fanfnir_back.Models.Carteiras", b =>
                {
                    b.Navigation("AportesMetas");

                    b.Navigation("Assinaturas");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("fanfnir_back.Models.Categorias", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("OrcamentosMensais");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("fanfnir_back.Models.Metas", b =>
                {
                    b.Navigation("AportesMetas");
                });

            modelBuilder.Entity("fanfnir_back.Models.OpenFinanceConnection", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("fanfnir_back.Models.Usuarios", b =>
                {
                    b.Navigation("AportesMetas");

                    b.Navigation("Assinaturas");

                    b.Navigation("Carteiras");

                    b.Navigation("Categorias");

                    b.Navigation("Metas");

                    b.Navigation("OrcamentosMensais");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
